name: bimbelbeta

services:
  postgres:
    image: postgres:18-alpine
    container_name: bimbelbeta-postgres
    environment:
      POSTGRES_DB: bimbelbeta
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "6969:5432"
    volumes:
      - bimbelbeta_postgres_data:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

volumes:
  bimbelbeta_postgres_data:
